### ISSUE TITLE
User not created when "Deployed to Heroku", or cannot add the site via cli

### ISSUE THREAD

**Issue by arupsarkar** [SFDO-Tooling/MetaCI#271]
I used the process of deploying to heroku the site got deployed successfully but the default user was not created. When I click on the "Login" on the top right hand corner I get the following error.

Ooops!!! 500
Looks like something went wrong!
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

Additionally, When I am trying to add the site using `metaci site add` after filling in all the details I get the following error.

`Traceback (most recent call last):
  File "/Users/arup.sarkar/.pyenv/versions/cci/bin/metaci", line 11, in <module>
    sys.exit(main())
  File "/Users/arup.sarkar/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/arup.sarkar/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/arup.sarkar/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/arup.sarkar/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/arup.sarkar/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/arup.sarkar/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/arup.sarkar/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/metaci_cli/cli/config.py", line 150, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/arup.sarkar/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/arup.sarkar/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/metaci_cli/cli/commands/site.py", line 228, in site_add
    env['CONNECTED_APP_CALLBACK_URL'] = connected_app.callback_url
AttributeError: 'NoneType' object has no attribute 'callback_url'`

**Comment by arupsarkar** [comment]
Also, wanted to mention the steps I followed
1) Created a Dev Hub
2) Created a .crt, .key file as mentioned in https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_key_and_cert.htm
3) Created a connected app, "Callback URL" I specified http://localhost:8080/callback. I also attached the .crt as digital signature (created in the previous step).
4) used the following command `sfdx force:auth:jwt:grant` for authorization via JWT as mentioned in https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_jwt_flow.htm. I got the following message
`Successfully authorized xxxxx@xxxxx.com with org ID 123456789012345123`
5)Now, I am trying to `metaci site add` filled app name, app shape, path to private key (same one used for JWT), client id (from dev hub same one used for JWT)

after putting in the client id and hitting enter I am getting the error mentioned above. Can someone please help.

**Comment by cdcarter** [comment]
You'll need to use `heroku run python manage.py createsuperuser` to get a superuser created.

I'm not so sure about that error with site add. I'm _guessing_ that you don't have cumulusci configured with a connected_app locally. @jlantz any ideas?

**Comment by arupsarkar** [comment]
@cdcarter thanks so much for answering. I will run the command you mentioned and update here, for the cumulusci configuration it is configured, as well as sfdx in my local. 
`(cci) [kv-movies-app (feature/KMA-3)]$ cci
Usage: cci [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  flow     Commands for finding and running flows for a...
  org      Commands for connecting and interacting with...
  project  Commands for interacting with project...
  service  Commands for connecting services to the...
  shell    Drop into a python shell
  task     Commands for finding and running tasks for a...
  version  Print the current version of CumulusCI`
and sfdx is
`(cci) [kv-movies-app (feature/KMA-3)]$ sfdx
Usage: sfdx COMMAND

Help topics, type sfdx help TOPIC for more details:

 force    tools for the Salesforce developer
 help     display help for <%= config.bin %>
 plugins  add/remove/create CLI plug-ins
 update   update the sfdx CLI`

**Comment by arupsarkar** [comment]
@cdcarter This is the output when I am running `heroku run python manage.py createsuperuser --app sfdc-ci`

> Console output

`Running python manage.py createsuperuser on ⬢ sfdc-ci... up, run.8044 (Free)`

`WARNING: You acknowledge and agree that the CLI tool may collect usage information, user environment, and crash reports for the purposes of providing services or functions that are relevant to use of the CLI tool and product improvements.`

`Successfully authorized arup.devhub@kv.com with org ID 00Df2000000D15dEAC`

`/app/.heroku/python/lib/python2.7/site-packages/environ/environ.py:615: UserWarning: /app/config/settings/.env doesn't exist - if you're not configuring your environment separately, create one.
  "environment separately, create one." % env_file)
Username: Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 63, in execute
    return super(Command, self).execute(*args, **options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 116, in handle
    username = self.get_input_data(self.username_field, input_msg, default_username)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 192, in get_input_data
    raw_value = input(message)
EOFError`
